# Standard library
from typing import Union

# Third-party
import matplotlib.pyplot as plt
import torch
import wandb

# First-party
from neural_lam import metrics
from neural_lam.models.ar_prob_model import ARProbModel
from neural_lam.models.graph_diff import GraphDiff

# Local
from ..config import NeuralLAMConfig
from ..datastore import BaseDatastore


class GraphCRPS(ARProbModel):
    """
    Continuous Ranked Probability Score (CRPS) Model.

    Ensemble members are generated by feeding a random noise vector to the
    GraphDiff backbone, which is shared with graph_det/EDM/FM/SI. Like graph_fm,
    graph_det and GraphEFM, each member is predicted as a normalized residual
    that is rescaled by the one-step difference statistics, added to the
    previous state and clamped to the valid range.
    """

    def __init__(
        self,
        args,
        config: NeuralLAMConfig,
        datastore: BaseDatastore,
        datastore_boundary: Union[BaseDatastore, None],
        datastore_atmosphere: Union[BaseDatastore, None],
        **kwargs,
    ):
        super().__init__(
            args,
            config,
            datastore,
            datastore_boundary,
            datastore_atmosphere,
            **kwargs,
        )
        self.val_metrics.update(
            {
                "ens_crps": [],
            }
        )

        if args.backbone_model == "graph_diff":
            print("Using GraphDiff")
            self.model = GraphDiff(
                args,
                config,
                datastore,
                datastore_boundary,
                datastore_atmosphere,
            )
        else:
            raise NotImplementedError(
                f"Unknown backbone model: {args.backbone_model}"
            )

        # Compute indices and define clamping functions, matching
        # BaseGraphModel (and thereby graph_fm) and GraphEFM
        self.prepare_clamping_params(config, datastore)

    def predict_step(
        self,
        prev_state,
        prev_prev_state,
        forcing,
        boundary_forcing,
        atmosphere_forcing,
    ):
        """
        Step state one step ahead using prediction model, X_{t-1}, X_t -> X_t+1
        prev_state: (B, num_grid_nodes, feature_dim), X_t
        prev_prev_state: (B, num_grid_nodes, feature_dim), X_{t-1}
        forcing: (B, num_grid_nodes, forcing_dim)
        boundary_forcing: (B, num_boundary_nodes, boundary_forcing_dim)
        atmosphere_forcing: (B, num_atmosphere_nodes, atmosphere_forcing_dim)


        Returns:
        next_state: (B, N_grid, d_state),
            predicted weather state X_{t+1} at time t+1
        pred_std: (B, N_grid, d_state) if output_std, else None
        """
        if prev_prev_state is not None:
            input_grid = torch.cat(
                (prev_state, prev_prev_state, forcing), dim=-1
            )
        else:
            input_grid = torch.cat((prev_state, forcing), dim=-1)
        # (B, N_grid, d_input)

        z = torch.randn(
            prev_state.shape[0],
            self.model.noise_dim,
            device=prev_state.device,
            generator=self._get_generator(prev_state.device),
        )

        net_output = self.model(
            input_grid,
            noise_level=z,
            cond=None,
            boundary_forcing=boundary_forcing,
            atmosphere_forcing=atmosphere_forcing,
        )  # (B, N_grid, d_grid_out)

        # NOTE: From here on this is identical to BaseGraphModel.predict_step
        # (graph_fm) and to graph_det, so that all models sharing the GraphDiff
        # backbone use the same residual parametrization and the same output
        # clamping. --pred_residual has no effect here, the residual
        # parametrization is always used.
        if self.output_std:
            pred_delta_mean, pred_std_raw = net_output.chunk(
                2, dim=-1
            )  # both (B, num_grid_nodes, d_f)
            # NOTE: The predicted std. is not scaled in any way here
            # linter for some reason does not think softplus is callable
            # pylint: disable-next=not-callable
            pred_std = torch.nn.functional.softplus(pred_std_raw)
        else:
            pred_delta_mean = net_output
            pred_std = None

        # Rescale with one-step difference statistics
        rescaled_delta_mean = pred_delta_mean * self.diff_std + self.diff_mean

        # Clamp values to valid range (also add the delta to the previous state)
        new_state = self.get_clamped_new_state(rescaled_delta_mean, prev_state)

        return new_state, pred_std

    def training_step(self, batch):
        """
        Train on single batch
        batch consists of:
        init_states: (B, 2, num_interior_nodes, d_features)
        target_states: (B, pred_steps, num_interior_nodes, d_features)
        forcing: (B, pred_steps, num_interior_nodes, d_forcing),
        boundary_forcing:
            (B, pred_steps, num_boundary_nodes, d_boundary_forcing),
            where index 0 corresponds to index 1 of init_states
        """
        (
            init_states,
            target_states,
            forcing,
            boundary_forcing,
            atmosphere_forcing,
            _,
        ) = batch

        trajectories = self.sample_trajectories(
            init_states,
            forcing,
            boundary_forcing,
            atmosphere_forcing,
            ensemble_size=2,
        )

        crps_batch = metrics.afcrps_ens(
            trajectories,
            target_states,
            None,
            average_grid=False,
            sum_vars=False,
            alpha=self.args.crps_alpha,
        )  # (B, pred_steps, d_f)
        # prediction: (B, pred_steps, num_interior_nodes, d_f)
        # pred_std: (B, pred_steps, num_interior_nodes, d_f) or (d_f,)
        # loss_batch: (B, pred_steps)
        loss_batch = metrics.mask_and_reduce_metric(
            crps_batch / self.per_var_std,
            mask=self.loss_mask,
            average_grid=True,
            sum_vars=True,
        )

        # Compute loss - mean over unrolled times and batch
        batch_loss = torch.mean(loss_batch)

        log_dict = {"train_loss": batch_loss}
        self.log_dict(
            log_dict,
            prog_bar=True,
            on_step=True,
            on_epoch=True,
            sync_dist=True,
            batch_size=batch[0].shape[0],
        )
        return batch_loss

    def validation_step(self, batch, *args):
        """
        Run validation on single batch
        """
        super().validation_step(batch, *args)
        batch_idx = args[0]
        (
            trajectories,
            target_states,
            spread_squared_batch,
            ens_mse_batch,
        ) = self.ensemble_step(batch)
        self.val_metrics["spread_squared"].append(spread_squared_batch)
        self.val_metrics["ens_mse"].append(ens_mse_batch)
        crps_batch = metrics.crps_ens(
            trajectories,
            target_states,
            None,
            mask=self.loss_mask,
            average_grid=True,
            sum_vars=False,
        )
        self.val_metrics["ens_crps"].append(crps_batch)

        if (
            self.trainer.is_global_zero
            and batch_idx == 0
            and self.n_example_pred > 0
        ):
            # For now use val_steps_to_log to determine which steps
            # to make these plots for
            plot_log_steps = list(
                filter(
                    lambda s: s <= target_states.shape[1],
                    self.args.val_steps_to_log,
                )
            )
            # Plot forecasts
            traj_plots = self.plot_ensemble_examples(
                batch,
                n_examples=self.n_example_pred,
                prediction=trajectories,
                time_steps=plot_log_steps,
                log=False,
            )

            # Store plots
            log_plot_dict = {}
            log_plot_dict.update(
                {
                    f"prior_{plot_key}": plot
                    for plot_key, plot in traj_plots.items()
                }
            )

            if not self.trainer.sanity_checking:
                # Log all plots to wandb
                wandb.log(log_plot_dict)

            plt.close("all")
